name: Où investir
favicon: null
layout_spectrum: 0.727656
typography_spectrum: 0.4892293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#41485a'
    - '#1b143d'
    - '#f7d3a1'
    - '#ac9f6a'
  brandStrength: 0.4074259
  lightness: 0.5447099
  saturation: 0.8070117
  rhythmicContrast: 0.0420199
purpose: []
