layout_spectrum: 0.727656
typography_spectrum: 0.4892293
color:
  saturation: 0.8070117
  lightness: 0.5447099
  brandStrength: 0.4074259
  rhythmicContrast: 0.0420199
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Ou investir
