typography_spectrum: 0.4892293
color:
  brandColors:
    - '#ffffff'
    - '#41485a'
    - '#1b143d'
    - '#f7d3a1'
    - '#ac9f6a'
  brandStrength: 0.4074259
  lightness: 0.5447099
  saturation: 0.8070117
  rhythmicContrast: 0.0420199
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6046366
analytics:
  google: UA-74696886-1
  facebook: null
  twitter: null
name: Où investir
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Où investir
purpose: []
